### ISSUE TITLE
add language Viet nam

### ISSUE THREAD

**Issue by bvnsupport** [OwnGoalStudio/Touch-Viz#2]
/* No comment provided by engineer. */
"Animation Duration" = "Thời gian hoạt ảnh";

/* No comment provided by engineer. */
"Are you sure you want to reset all settings to their default values?" = "Bạn có chắc chắn muốn đặt lại tất cả cài đặt về giá trị mặc định không?";

/* No comment provided by engineer. */
"Border Color" = "Màu viền";

/* No comment provided by engineer. */
"Border Width" = "Chiều rộng viền";

/* No comment provided by engineer. */
"Credits:\n@LeoNatan: LNTouchVisualizer (MIT License)" = "Nhà cung cấp:\n@LeoNatan: LNTouchVisualizer (Giấy phép MIT)";

/* No comment provided by engineer. */
"Displays touch indicators only during screen recording." = "Chỉ hiển thị các chỉ báo cảm ứng trong khi ghi màn hình.";

/* No comment provided by engineer. */
"Effects" = "Các hiệu ứng";

/* No comment provided by engineer. */
"Enable Touch-Viz" = "Bật/Tắt Touch-Viz";

/* No comment provided by engineer. */
"Fill Color" = "Tô màu";

/* No comment provided by engineer. */
"Fill Size" = "Kích thước vòng tròn cảm ứng";

/* No comment provided by engineer. */
"General" = "Chung";

/* No comment provided by engineer. */
"Lift Scale" = "Kích thước của hiệu ứng";

/* No comment provided by engineer. */
"Morph Effect" = "Hiệu ứng biến hình";

/* No comment provided by engineer. */
"Only for Recording" = "Chỉ hiển thị khi ghi màn hình";

/* No comment provided by engineer. */
"Please check your network connection and try again later by tapping the screen." = "Vui lòng kiểm tra kết nối mạng của bạn và thử lại sau bằng cách nhấn vào màn hình.";

/* No comment provided by engineer. */
"Please check your purchase of “%@” in Sileo." = "Vui lòng kiểm tra giao dịch mua “%@” của bạn trong Sileo.";

/* No comment provided by engineer. */
"Reset" = "Đặt lại";

/* No comment provided by engineer. */
"Reset to Default" = "Đặt lại tất cả cài đặt";

/* No comment provided by engineer. */
"Touch Colors" = "Màu sắc cảm ứng";

/* No comment provided by engineer. */
"Touch-Viz" = "Touch-Viz";

/* No comment provided by engineer. */
"Touch-Viz has been turned off from Control Center." = "Touch-Viz đã bị tắt khỏi Trung tâm điều khiển.";

/* No comment provided by engineer. */
"Touch-Viz has been turned on from Control Center." = "Touch-Viz đã được bật từ Trung tâm điều khiển.";

/* No comment provided by engineer. */
"Tracking Effect" = "Hiệu ứng theo dõi";

/* No comment provided by engineer. */
"Use Touch Colors" = "Sử dụng màu cảm ứng";

/* No comment provided by engineer. */
"v%@ - @Lessica" = "v%@ - @Lessica";

/* No comment provided by engineer. */
"Verification Failed" = "Xác minh không hoàn thành";

/* No comment provided by engineer. */
"Verifying License" = "Xác minh Giấy phép";

**Comment by Lessica** [comment]
Thank you. We've updated and added some texts.
