### ISSUE TITLE
"Pirated Tweak" after changing iOS language

### ISSUE THREAD

**Issue by ruucat** [OwnGoalStudio/Touch-Viz#3]
Steps to reproduce:
1. Install Touch-Viz from Havoc, enable it and respring
2. Change system language during jailbroken state
3. Get "Pirated Tweak" alert.
I tried to reinstall tweak from havoc multiple times, but it doesnt help at all.
Maybe I should remove some files to get it working again?

**Comment by ruucat** [comment]
Should I completely reinstall jb environment then?

**Comment by 4rtz1z** [comment]
i have this problem too, i've tried uninstall and reinstall, uninstall re-jb reinstall

**Comment by Lessica** [comment]
Fixed in [v3.1](https://github.com/Lessica/Touch-Viz/releases/tag/v3.1)

**Comment by Lessica** [comment]
Fixed in [v2.11](https://havoc.app/package/touchvis/changes) and [v3.1](https://github.com/Lessica/Touch-Viz/releases/tag/v3.1).
