### ISSUE TITLE
[REQUEST] Add ability to disable touch feedback from iPad keyboard/trackpad

### ISSUE THREAD

**Issue by hipp013** [OwnGoalStudio/Touch-Viz#5]
Currently, Touch-Viz shows touch feedback from inputs on the Magic Keyboard trackpad. However, that touch feedback does not correspond to where the cursor is on the screen, but rather corresponds to the position of my finger(s) on the trackpad. (e.g. touching top-left corner of trackpad = touch indicator appears in top left of screen)

This doesn't appear to be a bug per se, but as a result of this behavior, using the trackpad on an iPad magic keyboard looks like this:

![E029FD80-1A68-42CC-9EC2-E049CAAADDD3](https://github.com/user-attachments/assets/93cbe0d1-6cd3-4dd5-b3ca-9a0a7d6da4af)
_Pictured: Screen touch feedback works great, but trackpad touch feedback follows position of finger on trackpad rather than following on-screen cursor_

This is nice for when I want to see multi-finger trackpad gestures on the screen, but it creates confusion when using one finger to move the cursor. Since the Touch-Viz touch feedback moves independently of the on-screen cursor, it creates what looks like two cursors on the screen. 

In my mind it is confusing and unnecessary to show touch feedback when moving the cursor, therefore I'm requesting one of the following:

- toggle to disable trackpad touch feedback entirely
- toggle to make one-finger trackpad gestures follow the on-screen cursor instead of showing exact touch location on trackpad

**Comment by Lessica** [comment]
Fixed by disabling all indirect touch event tracking in [v3.11](https://github.com/OwnGoalStudio/Touch-Viz/releases/tag/v3.11).
